#
# pass for allowlisted (public) routes
# block for denylisted routes
#
rules:
  pass: 
    - api/v2/barong/identity
    - api/v2/peatio/public
  block:
    - api/v2/barong/management
    - api/v2/peatio/management
